var string_common_vn = {
	"app_name": "Cẩm Nang Liên Quân",
  "btn_back": "Trở lại",
  "btn_info": "Thông Tin",
  "btn_skin": "Trang Phục",
  "info_common": "Thông Tin Chung",
  "hero_position": "Vai trò",
  "hero_special": "Đặc biệt",
  "hero_lane": "Vị trí",
  "hero_skill": "Kỹ Năng",
  "btn_tap": "*Hãy Tap vào kỹ năng cần xem",
  "btn_tap_item": "*Hãy Tap vào trang bị cần xem",
  "btn_tap_spell": "*Hãy Tap vào độc chiêu cần xem",
  "normal_skill": "Đánh thường",
  "normal_skill_info": "Là chiêu đánh mặc định của mỗi Anh hùng, không thời gian hồi chiêu, không tốn năng lượng.",
  "skill_up": "Tăng chiêu thức",
  "hero_special_skill": "Độc Chiêu",
  "hero_special_skill_info": "Chọn 1 trong các chiêu sau",
  "hero_rune": "Ngọc",
  "hero_rune2": "Ngọc cấp 2",
  "hero_rune3": "Ngọc cấp 3",
  "item_title": "Trang bị",
  "full_set": "Gợi ý full đồ",
  "hero_story": "Câu truyện của",
  "updating": "Đang cập nhật...",
  "wall_download": "Tải Ảnh Nền",
  "review_info": "Mọi người cùng Đánh Giá ứng dụng để ngày càng phát triển nhé!",
  "review": "Đánh Giá",
  "next_time": "Lần Sau",
  "coming_soon": "Coming soon",
  "coming_soon_info": "Sắp Tới Có Gì Mới?",
  "what_new": "Có gì mới?!",
  "thanks_for": "Ứng dụng của mình chỉ hướng dẫn mọi người làm sao chơi Liên Quân Mobile cho tốt hơn, vì thế mọi ý kiến đóng góp xin mọi người gửi qua mail hoặc gửi tin nhắn thông qua Facebook nhé! Cảm ơn!!",
  "btn_mail": "Gửi mail",
  "mail_status": "Đừng quên Đánh Giá ứng dụng nha mọi người! :D",
  "aov_download": "Link tải game Liên Quân Mobile",
  "btn_close": "Đóng",
  "all_hero": "Tất Cả",
  "warr_hero": "Đấu Sĩ",
  "tank_hero": "Đỡ Đòn",
  "assa_hero": "Sát Thủ",
  "mage_hero": "Pháp Sư",
  "mark_hero": "Xạ Thủ",
  "supo_hero": "Trợ Thủ",
  "find_hero": "Anh hùng bạn tìm ai...",
  "read_more": "Xem thêm...",
  "connect_wifi": "*Cần kết nối Wifi, 4G, 3G,.. rồi mới xem được video, tin tức hoặc tải ảnh nền!!",
  "connect_info": "*Mở lại ứng dụng sau khi kết nối Wifi, 3G,..",
  "update_btn": "Cập nhật",
  "update_info": "Đã có bản cập nhật mới nhất, cả nhà cùng update nhé!!",
  "update_title": "Cập nhật ứng dụng",
  "liked": "Đã thích",
  "no_like": "Bạn chưa thích Tin tức nào!!",
  "news_more_alert": "*Có thể tải lại tin tức sau 1 phút!",
};